name: phppackagename
phpversions: 5.3 5.4 5.5 5.6 7.0 7.1 7.2 7.3 7.4
services:
  php:
    type: php:7.4
    via: cli
    xdebug: true
  php7:
    type: php:7.2
    via: cli
    xdebug: true
  php5:
    type: php:5.6
    via: cli
    xdebug: true
tooling:
  composer:
    service: php
    description: Run composer commands on php latest
    cmd: composer --ansi
  composer7:
    service: php7
    description: Run composer commands on php 7.2
    cmd: composer --ansi
  composer5:
    service: php5
    description: Run composer commands on php 5.6
    cmd: composer --ansi
  php:
    service: php
    cmd: php
  php7:
    service: php7
    cmd: php
  php5:
    service: php5
    cmd: php
  phpunit:
    service: php
    description: Run phpunit latest testing
    cmd:
      - cd /app && export COMPOSER_VENDOR_DIR=vendor && export COMPOSER="./composer.json" && composer install
      - cd /app && php ./vendor/bin/phpunit --verbose --configuration ./phpunit.xml
  phpunit7:
    service: php7
    description: Run phpunit 7.2 testing
    cmd:
      - cd /app && export COMPOSER_VENDOR_DIR=vendor7 && export COMPOSER="./composer7.json" && composer install
      - cd /app && php ./vendor7/bin/phpunit --verbose --configuration ./phpunit7.xml
  phpunit5:
    service: php5
    description: Run phpunit 5.6 testing
    cmd:
      - cd /app && export COMPOSER_VENDOR_DIR=vendor5 && export COMPOSER="./composer5.json" && composer install
      - cd /app && php ./vendor5/bin/phpunit --verbose --configuration ./phpunit5.xml
